/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkRouteImport } from './routes/_layout/work'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutPhotosRouteImport } from './routes/_layout/photos'
import { Route as LayoutMusicRouteImport } from './routes/_layout/music'
import { Route as LayoutBlogRouteImport } from './routes/_layout/blog'
import { Route as LayoutBlogBlogIdRouteImport } from './routes/_layout/blog_/$blogId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkRoute = LayoutWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPhotosRoute = LayoutPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMusicRoute = LayoutMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogRoute = LayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogBlogIdRoute = LayoutBlogBlogIdRouteImport.update({
  id: '/blog_/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/blog': typeof LayoutBlogRoute
  '/music': typeof LayoutMusicRoute
  '/photos': typeof LayoutPhotosRoute
  '/projects': typeof LayoutProjectsRoute
  '/work': typeof LayoutWorkRoute
  '/blog/$blogId': typeof LayoutBlogBlogIdRoute
}
export interface FileRoutesByTo {
  '/blog': typeof LayoutBlogRoute
  '/music': typeof LayoutMusicRoute
  '/photos': typeof LayoutPhotosRoute
  '/projects': typeof LayoutProjectsRoute
  '/work': typeof LayoutWorkRoute
  '/': typeof LayoutIndexRoute
  '/blog/$blogId': typeof LayoutBlogBlogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/blog': typeof LayoutBlogRoute
  '/_layout/music': typeof LayoutMusicRoute
  '/_layout/photos': typeof LayoutPhotosRoute
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_layout/work': typeof LayoutWorkRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/blog_/$blogId': typeof LayoutBlogBlogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/music'
    | '/photos'
    | '/projects'
    | '/work'
    | '/blog/$blogId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blog'
    | '/music'
    | '/photos'
    | '/projects'
    | '/work'
    | '/'
    | '/blog/$blogId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/blog'
    | '/_layout/music'
    | '/_layout/photos'
    | '/_layout/projects'
    | '/_layout/work'
    | '/_layout/'
    | '/_layout/blog_/$blogId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/work': {
      id: '/_layout/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof LayoutWorkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/photos': {
      id: '/_layout/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof LayoutPhotosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/music': {
      id: '/_layout/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof LayoutMusicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog': {
      id: '/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog_/$blogId': {
      id: '/_layout/blog_/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof LayoutBlogBlogIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBlogRoute: typeof LayoutBlogRoute
  LayoutMusicRoute: typeof LayoutMusicRoute
  LayoutPhotosRoute: typeof LayoutPhotosRoute
  LayoutProjectsRoute: typeof LayoutProjectsRoute
  LayoutWorkRoute: typeof LayoutWorkRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBlogBlogIdRoute: typeof LayoutBlogBlogIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBlogRoute: LayoutBlogRoute,
  LayoutMusicRoute: LayoutMusicRoute,
  LayoutPhotosRoute: LayoutPhotosRoute,
  LayoutProjectsRoute: LayoutProjectsRoute,
  LayoutWorkRoute: LayoutWorkRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBlogBlogIdRoute: LayoutBlogBlogIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
